export interface GalleryImage {
	id: string;
	src: string;
	alt: string;
	featured: boolean;
}

/**
 * Gallery image metadata
 *
 * This file is auto-generated by scripts/generate-gallery.ts
 * To regenerate, run: npm run generate-gallery
 *
 * To manually edit featured images, change the 'featured' property to true/false
 * Limit featured images to 5 for optimal carousel display
 */
export const galleryImages: GalleryImage[] = [
	{
		id: '000-acorn',
		src: '/gallery/000_acorn.webp',
		alt: 'Artwork: Acorn',
		featured: true
	},
	{
		id: '001-herculesebeetle',
		src: '/gallery/001_herculesebeetle.webp',
		alt: 'Artwork: Herculesebeetle',
		featured: true
	},
	{
		id: '002-fishsketch',
		src: '/gallery/002_fishsketch.webp',
		alt: 'Artwork: Fishsketch',
		featured: true
	},
	{
		id: '003-golduck',
		src: '/gallery/003_golduck.webp',
		alt: 'Artwork: Golduck',
		featured: true
	},
	{
		id: '004-briscoskunkpng',
		src: '/gallery/004_briscoskunk.png.webp',
		alt: 'Artwork: Briscoskunk.png',
		featured: true
	},
	{
		id: 'animattempt',
		src: '/gallery/animattempt.gif',
		alt: 'Artwork: Animattempt',
		featured: false
	},
	{
		id: 'ate',
		src: '/gallery/ate.webp',
		alt: 'Artwork: Ate',
		featured: false
	},
	{
		id: 'ax2',
		src: '/gallery/ax2.webp',
		alt: 'Artwork: Ax2',
		featured: false
	},
	{
		id: 'buganimation-ezgifcom-video-to-gif-converter',
		src: '/gallery/buganimation-ezgif.com-video-to-gif-converter.gif',
		alt: 'Artwork: Buganimation Ezgif.com Video To Gif Converter',
		featured: false
	},
	{
		id: 'catnight',
		src: '/gallery/catnight.webp',
		alt: 'Artwork: Catnight',
		featured: false
	},
	{
		id: 'ciga',
		src: '/gallery/ciga.webp',
		alt: 'Artwork: Ciga',
		featured: false
	},
	{
		id: 'cockatricemon',
		src: '/gallery/cockatricemon.webp',
		alt: 'Artwork: Cockatricemon',
		featured: false
	},
	{
		id: 'colors',
		src: '/gallery/colors.webp',
		alt: 'Artwork: Colors',
		featured: false
	},
	{
		id: 'donnie',
		src: '/gallery/donnie.webp',
		alt: 'Artwork: Donnie',
		featured: false
	},
	{
		id: 'dragonthig',
		src: '/gallery/dragonthig.webp',
		alt: 'Artwork: Dragonthig',
		featured: false
	},
	{
		id: 'emogarf',
		src: '/gallery/emogarf.webp',
		alt: 'Artwork: Emogarf',
		featured: false
	},
	{
		id: 'fantasticmrguy',
		src: '/gallery/fantasticmrguy.webp',
		alt: 'Artwork: Fantasticmrguy',
		featured: false
	},
	{
		id: 'friendlyfrogs',
		src: '/gallery/friendlyfrogs.webp',
		alt: 'Artwork: Friendlyfrogs',
		featured: false
	},
	{
		id: 'greenpinkcatidk',
		src: '/gallery/greenpinkcatidk.webp',
		alt: 'Artwork: Greenpinkcatidk',
		featured: false
	},
	{
		id: 'kindabeautiful',
		src: '/gallery/kindabeautiful.webp',
		alt: 'Artwork: Kindabeautiful',
		featured: false
	},
	{
		id: 'kiwii-nofilter',
		src: '/gallery/kiwii_nofilter.webp',
		alt: 'Artwork: Kiwii Nofilter',
		featured: false
	},
	{
		id: 'levi',
		src: '/gallery/levi.webp',
		alt: 'Artwork: Levi',
		featured: false
	},
	{
		id: 'nemesis',
		src: '/gallery/nemesis.webp',
		alt: 'Artwork: Nemesis',
		featured: false
	},
	{
		id: 'newmongeenbird',
		src: '/gallery/newmongeenbird.webp',
		alt: 'Artwork: Newmongeenbird',
		featured: false
	},
	{
		id: 'newstart',
		src: '/gallery/newstart.webp',
		alt: 'Artwork: Newstart',
		featured: false
	},
	{
		id: 'nomouth',
		src: '/gallery/nomouth.webp',
		alt: 'Artwork: Nomouth',
		featured: false
	},
	{
		id: 'nova-pink',
		src: '/gallery/nova_pink.webp',
		alt: 'Artwork: Nova Pink',
		featured: false
	},
	{
		id: 'oobert',
		src: '/gallery/oobert.webp',
		alt: 'Artwork: Oobert',
		featured: false
	},
	{
		id: 'pallett1',
		src: '/gallery/pallett1.webp',
		alt: 'Artwork: Pallett1',
		featured: false
	},
	{
		id: 'pallett2',
		src: '/gallery/pallett2.webp',
		alt: 'Artwork: Pallett2',
		featured: false
	},
	{
		id: 'person',
		src: '/gallery/person.webp',
		alt: 'Artwork: Person',
		featured: false
	},
	{
		id: 'refsheit',
		src: '/gallery/refsheit.webp',
		alt: 'Artwork: Refsheit',
		featured: false
	},
	{
		id: 'shadowrealm',
		src: '/gallery/shadowrealm.webp',
		alt: 'Artwork: Shadowrealm',
		featured: false
	},
	{
		id: 'sphynx',
		src: '/gallery/sphynx.webp',
		alt: 'Artwork: Sphynx',
		featured: false
	},
	{
		id: 'talkingoot',
		src: '/gallery/talkingoot.webp',
		alt: 'Artwork: Talkingoot',
		featured: false
	},
	{
		id: 'templeofthedog',
		src: '/gallery/templeofthedog.webp',
		alt: 'Artwork: Templeofthedog',
		featured: false
	},
	{
		id: 'times',
		src: '/gallery/times.webp',
		alt: 'Artwork: Times',
		featured: false
	},
	{
		id: 'waxtonsona',
		src: '/gallery/waxtonsona.webp',
		alt: 'Artwork: Waxtonsona',
		featured: false
	},
	{
		id: 'zaataz',
		src: '/gallery/Zaataz.webp',
		alt: 'Artwork: Zaataz',
		featured: false
	}
];

/**
 * Featured images for the home page carousel
 * Automatically filters images marked as featured and limits to 5
 */
export const featuredImages = galleryImages
	.filter((img) => img.featured)
	.slice(0, 5);

/**
 * Get all gallery images for the gallery page
 */
export const getAllGalleryImages = () => galleryImages;
