#!/usr/bin/env tsx

import { readdirSync, writeFileSync, existsSync } from 'node:fs';
import { basename, extname } from 'node:path';

interface GalleryImage {
	id: string;
	src: string;
	alt: string;
	featured: boolean;
}

const GALLERY_DIR = 'static/gallery';
const OUTPUT_FILE = 'src/lib/gallery-data.ts';
const FEATURED_COUNT = 5;

// Image extensions to include
const IMAGE_EXTENSIONS = new Set(['.jpg', '.jpeg', '.png', '.webp', '.gif']);

function generateAltText(filename: string): string {
	// Remove extension and numbers
	let name = basename(filename, extname(filename));

	// Remove leading numbers like "007_"
	name = name.replace(/^\d+_/, '');

	// Replace underscores and hyphens with spaces
	name = name.replace(/[_-]/g, ' ');

	// Capitalize first letter of each word
	name = name
		.split(' ')
		.map(word => word.charAt(0).toUpperCase() + word.slice(1))
		.join(' ');

	return `Artwork: ${name}`;
}

function generateId(filename: string): string {
	// Remove extension
	let id = basename(filename, extname(filename));

	// Convert to lowercase and replace spaces/underscores with hyphens
	id = id.toLowerCase().replace(/[_\s]+/g, '-');

	// Remove any characters that aren't alphanumeric or hyphens
	id = id.replace(/[^a-z0-9-]/g, '');

	return id;
}

function scanGalleryImages(): GalleryImage[] {
	if (!existsSync(GALLERY_DIR)) {
		console.error(`Error: Gallery directory not found: ${GALLERY_DIR}`);
		process.exit(1);
	}

	const files = readdirSync(GALLERY_DIR);
	const imageFiles = files.filter(file =>
		IMAGE_EXTENSIONS.has(extname(file).toLowerCase())
	);

	if (imageFiles.length === 0) {
		console.warn('Warning: No images found in gallery directory');
		return [];
	}

	// Sort files alphabetically
	imageFiles.sort((a, b) => a.localeCompare(b));

	const images: GalleryImage[] = imageFiles.map((file, index) => {
		const id = generateId(file);
		const alt = generateAltText(file);
		const src = `/static/gallery/${file}`;

		// Mark first FEATURED_COUNT images as featured
		const featured = index < FEATURED_COUNT;

		return {
			id,
			src,
			alt,
			featured
		};
	});

	return images;
}

function generateTypeScriptFile(images: GalleryImage[]): string {
	const imageEntries = images.map(img => {
		const fields = [
			`\t\tid: '${img.id}'`,
			`\t\tsrc: '${img.src}'`,
			`\t\talt: '${img.alt}'`,
			`\t\tfeatured: ${img.featured}`
		];

		return `\t{\n${fields.join(',\n')}\n\t}`;
	});

	return `export interface GalleryImage {
	id: string;
	src: string;
	alt: string;
	featured: boolean;
}

/**
 * Gallery image metadata
 *
 * This file is auto-generated by scripts/generate-gallery.ts
 * To regenerate, run: npm run generate-gallery
 *
 * To manually edit featured images, change the 'featured' property to true/false
 * Limit featured images to 5 for optimal carousel display
 */
export const galleryImages: GalleryImage[] = [
${imageEntries.join(',\n')}
];

/**
 * Featured images for the home page carousel
 * Automatically filters images marked as featured and limits to 5
 */
export const featuredImages = galleryImages
	.filter((img) => img.featured)
	.slice(0, 5);

/**
 * Get all gallery images for the gallery page
 */
export const getAllGalleryImages = () => galleryImages;
`;
}

function main() {
	const images = scanGalleryImages();

	console.log(`Found ${images.length} images`);
	console.log(`Marked first ${FEATURED_COUNT} as featured for carousel`);

	const tsContent = generateTypeScriptFile(images);

	writeFileSync(OUTPUT_FILE, tsContent, 'utf-8');

	console.log(`Generated ${OUTPUT_FILE}`);
}

main();
